version: '3'
services:

  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./extras/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "false"
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"

